apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: profile-app
      env: blue
  template:
    metadata:
      labels:
        app: profile-app
        env: blue
    spec:
      containers:
      - name: profile-app
        image: docker.io/library/taupatupatu-profile:v1
        imagePullPolicy: "Never" # for local in minikube
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
        ports:
        - containerPort: 8086
        startupProbe:
          httpGet:
            path: /health
            port: 8086
          failureThreshold: 30
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8086
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8086
          initialDelaySeconds: 15
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: profile-service-blue
spec:
  selector:
    app: profile-app
    env: blue
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8086