apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: NodePort
  # Метки селектора, использованные в шаблоне подов при создании объекта Deployment.
  selector:
    app: auth
  ports:
    - name: http
      protocol: TCP
      port: 8080 # Порт сетевого балансировщика, на котором будут обслуживаться пользовательские запросы.
      targetPort: 8081 # Порт контейнера, на котором доступно приложение.
      #nodePort: 30007 # Необязательное поле. По умолчанию и для удобства плоскость управления Kubernetes выделит порт из диапазона (по умолчанию: 30000-32767).